name: Build and Deploy to Github Pages
on:
  push:                   # triggered by any push to master branch
    branches:
      - master
  workflow_dispatch:      # manual trigger (without any input)

jobs:
  Build_and_Deploy_to_GitHub_Pages:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out current repo
        uses: actions/checkout@v4.1.1
      - name: Cache dependencies on servers
        uses: actions/cache@v4.0.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build and deploy
        uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          branch: 'gh-pages'
          token: ${{ secrets.GITHUB_TOKEN }}
          # for preventing below error during 'git push'
          #     error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
          #     send-pack: unexpected disconnect while reading sideband packet
          #     fatal: the remote end hung up unexpectedly
          #     Everything up-to-date
          pre_build_commands: git config --global http.version HTTP/1.1; git config --global http.postBuffer 524288000;
