name: Update ATB Release Version
on:
  workflow_dispatch:
    inputs:
      atb_release_version:
        description: 'ATB Release Version (e.g. 0.20.2)'
        required: true

jobs:
  Update-ATB-Release-Version:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Check out current repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SITE_TOKEN }}   # GitHub Personal Access Token; required only for triggering the on-push event in the other workflow file (refer to https://github.com/orgs/community/discussions/25702#discussioncomment-3248827)
      - name: Update ATB release version
        run: |
          (Get-Content _config.yml) -replace "^atb_release_version:.*$", "atb_release_version: ${{ inputs.atb_release_version }}" | Out-File -encoding ASCII _config.yml
      - name: Commit and push changes
        run: |
          git config --global user.name "Zheng Wang"
          git config --global user.email "zheng-wang@users.noreply.github.com"
          git add -A
          git commit -m "update ATB release version"
          git push
