name: Update ATB Version from Latest Tag
on: [workflow_dispatch]
jobs:
  Update-ATB-Version-from-Latest-Tag:
    runs-on: windows-latest
    steps:
      - name: Get latest ATB tag name
        id: get-latest-atb-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: apitestbase/apitestbase
      - name: Remove 'v' from the tag name
        id: get-latest-atb-version
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: 'v'
          string: '${{ steps.get-latest-atb-tag.outputs.tag }}'
          replace-with: ''
      - name: Check out current web site repo
        uses: actions/checkout@v3
      - name: Update ATB version
        run: |
          (Get-Content _config.yml) -replace "^atb_version:.*$", "atb_version: ${{ steps.get-latest-atb-version.outputs.replaced }}" | Out-File -encoding ASCII _config.yml
      - name: Commit and push changes
        run: |
          git config --global user.name "Zheng Wang"
          git config --global user.email "zheng-wang@users.noreply.github.com"
          git add -A
          git commit -m "update ATB version to latest tag"
          git push
